// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';


function holeFactory(number, par, yards) {
  return /* record */[
          /* number */number,
          /* par */par,
          /* yards */yards
        ];
}

var eastmoreland_001 = /* holes : :: */[
  /* record */[
    /* number */1,
    /* par */4,
    /* yards */311
  ],
  /* :: */[
    /* record */[
      /* number */2,
      /* par */4,
      /* yards */447
    ],
    /* :: */[
      /* record */[
        /* number */3,
        /* par */4,
        /* yards */337
      ],
      /* :: */[
        /* record */[
          /* number */4,
          /* par */4,
          /* yards */347
        ],
        /* :: */[
          /* record */[
            /* number */5,
            /* par */3,
            /* yards */210
          ],
          /* :: */[
            /* record */[
              /* number */6,
              /* par */5,
              /* yards */497
            ],
            /* :: */[
              /* record */[
                /* number */7,
                /* par */4,
                /* yards */410
              ],
              /* :: */[
                /* record */[
                  /* number */8,
                  /* par */3,
                  /* yards */227
                ],
                /* :: */[
                  /* record */[
                    /* number */9,
                    /* par */5,
                    /* yards */497
                  ],
                  /* :: */[
                    /* record */[
                      /* number */10,
                      /* par */4,
                      /* yards */334
                    ],
                    /* :: */[
                      /* record */[
                        /* number */11,
                        /* par */5,
                        /* yards */469
                      ],
                      /* :: */[
                        /* record */[
                          /* number */12,
                          /* par */3,
                          /* yards */167
                        ],
                        /* :: */[
                          /* record */[
                            /* number */13,
                            /* par */5,
                            /* yards */447
                          ],
                          /* :: */[
                            /* record */[
                              /* number */14,
                              /* par */4,
                              /* yards */383
                            ],
                            /* :: */[
                              /* record */[
                                /* number */15,
                                /* par */4,
                                /* yards */381
                              ],
                              /* :: */[
                                /* record */[
                                  /* number */16,
                                  /* par */4,
                                  /* yards */423
                                ],
                                /* :: */[
                                  /* record */[
                                    /* number */17,
                                    /* par */3,
                                    /* yards */169
                                  ],
                                  /* :: */[
                                    /* record */[
                                      /* number */18,
                                      /* par */4,
                                      /* yards */457
                                    ],
                                    /* [] */0
                                  ]
                                ]
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]
  ]
];

var eastmoreland = /* record */[
  /* name */"Eastmoreland",
  eastmoreland_001
];

exports.holeFactory = holeFactory;
exports.eastmoreland = eastmoreland;
/* No side effect */
