// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");

function holeFactory(number, par, yards) {
  return /* record */[
          /* number */number,
          /* par */par,
          /* yards */yards
        ];
}

function scoreFactory(strokes, fairway, green, putts) {
  return /* record */[
          /* strokes */strokes,
          /* fairway */fairway,
          /* green */green,
          /* putts */putts
        ];
}

function totalYards(course) {
  return List.fold_left((function (acc, cur) {
                return acc + cur[/* yards */2] | 0;
              }), 0, course[/* holes */1]);
}

var eastmoreland_001 = /* holes : :: */[
  /* record */[
    /* number */1,
    /* par */4,
    /* yards */311
  ],
  /* :: */[
    /* record */[
      /* number */2,
      /* par */4,
      /* yards */447
    ],
    /* :: */[
      /* record */[
        /* number */3,
        /* par */4,
        /* yards */337
      ],
      /* :: */[
        /* record */[
          /* number */4,
          /* par */4,
          /* yards */347
        ],
        /* :: */[
          /* record */[
            /* number */5,
            /* par */3,
            /* yards */210
          ],
          /* :: */[
            /* record */[
              /* number */6,
              /* par */5,
              /* yards */497
            ],
            /* :: */[
              /* record */[
                /* number */7,
                /* par */4,
                /* yards */410
              ],
              /* :: */[
                /* record */[
                  /* number */8,
                  /* par */3,
                  /* yards */227
                ],
                /* :: */[
                  /* record */[
                    /* number */9,
                    /* par */5,
                    /* yards */497
                  ],
                  /* :: */[
                    /* record */[
                      /* number */10,
                      /* par */4,
                      /* yards */334
                    ],
                    /* :: */[
                      /* record */[
                        /* number */11,
                        /* par */5,
                        /* yards */469
                      ],
                      /* :: */[
                        /* record */[
                          /* number */12,
                          /* par */3,
                          /* yards */167
                        ],
                        /* :: */[
                          /* record */[
                            /* number */13,
                            /* par */5,
                            /* yards */447
                          ],
                          /* :: */[
                            /* record */[
                              /* number */14,
                              /* par */4,
                              /* yards */383
                            ],
                            /* :: */[
                              /* record */[
                                /* number */15,
                                /* par */4,
                                /* yards */381
                              ],
                              /* :: */[
                                /* record */[
                                  /* number */16,
                                  /* par */4,
                                  /* yards */423
                                ],
                                /* :: */[
                                  /* record */[
                                    /* number */17,
                                    /* par */3,
                                    /* yards */169
                                  ],
                                  /* :: */[
                                    /* record */[
                                      /* number */18,
                                      /* par */4,
                                      /* yards */457
                                    ],
                                    /* [] */0
                                  ]
                                ]
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]
  ]
];

var eastmoreland = /* record */[
  /* name */"Eastmoreland",
  eastmoreland_001
];

function totalScore(round) {
  return List.fold_left((function (acc, cur) {
                return acc + cur[/* strokes */0] | 0;
              }), 0, round[/* scores */2]);
}

function percentFIR(scores) {
  var fairways = List.filter((function (fairway) {
            return fairway !== 0;
          }))(List.map((function (score) {
              return score[/* fairway */1];
            }), scores));
  var totalFairwaysHit = List.fold_left((function (acc, cur) {
          if (cur !== 1) {
            return acc;
          } else {
            return acc + 1 | 0;
          }
        }), 0, List.map((function (score) {
              return score[/* fairway */1];
            }), scores));
  return totalFairwaysHit / List.length(fairways);
}

function percentGIR(scores) {
  var totalGreensHit = List.fold_left((function (acc, cur) {
          if (cur !== 0) {
            return acc;
          } else {
            return acc + 1 | 0;
          }
        }), 0, List.map((function (x) {
              return x[/* green */2];
            }), scores));
  return totalGreensHit / List.length(scores);
}

function totalPutts(scores) {
  return List.fold_left((function (acc, cur) {
                return acc + cur | 0;
              }), 0, List.map((function (score) {
                    return score[/* putts */3];
                  }), scores));
}

var round1_002 = /* scores : :: */[
  /* record */[
    /* strokes */3,
    /* fairway : Yes */1,
    /* green : Yes */0,
    /* putts */1
  ],
  /* :: */[
    /* record */[
      /* strokes */5,
      /* fairway : Yes */1,
      /* green : MissLeft */2,
      /* putts */2
    ],
    /* :: */[
      /* record */[
        /* strokes */4,
        /* fairway : Yes */1,
        /* green : Yes */0,
        /* putts */2
      ],
      /* :: */[
        /* record */[
          /* strokes */5,
          /* fairway : Yes */1,
          /* green : Yes */0,
          /* putts */3
        ],
        /* :: */[
          /* record */[
            /* strokes */3,
            /* fairway : NoFairway */0,
            /* green : Yes */0,
            /* putts */2
          ],
          /* :: */[
            /* record */[
              /* strokes */5,
              /* fairway : MissRight */3,
              /* green : Yes */0,
              /* putts */2
            ],
            /* :: */[
              /* record */[
                /* strokes */4,
                /* fairway : Yes */1,
                /* green : MissShort */8,
                /* putts */1
              ],
              /* :: */[
                /* record */[
                  /* strokes */4,
                  /* fairway : NoFairway */0,
                  /* green : MissShort */8,
                  /* putts */1
                ],
                /* :: */[
                  /* record */[
                    /* strokes */6,
                    /* fairway : MissRight */3,
                    /* green : MissRight */6,
                    /* putts */2
                  ],
                  /* :: */[
                    /* record */[
                      /* strokes */4,
                      /* fairway : Yes */1,
                      /* green : Yes */0,
                      /* putts */2
                    ],
                    /* :: */[
                      /* record */[
                        /* strokes */5,
                        /* fairway : MissLeft */2,
                        /* green : Yes */0,
                        /* putts */2
                      ],
                      /* :: */[
                        /* record */[
                          /* strokes */3,
                          /* fairway : NoFairway */0,
                          /* green : MissLeft */2,
                          /* putts */1
                        ],
                        /* :: */[
                          /* record */[
                            /* strokes */4,
                            /* fairway : MissRight */3,
                            /* green : Yes */0,
                            /* putts */2
                          ],
                          /* :: */[
                            /* record */[
                              /* strokes */4,
                              /* fairway : Yes */1,
                              /* green : MissShort */8,
                              /* putts */1
                            ],
                            /* :: */[
                              /* record */[
                                /* strokes */7,
                                /* fairway : Yes */1,
                                /* green : MissLeft */2,
                                /* putts */1
                              ],
                              /* :: */[
                                /* record */[
                                  /* strokes */5,
                                  /* fairway : Yes */1,
                                  /* green : Yes */0,
                                  /* putts */3
                                ],
                                /* :: */[
                                  /* record */[
                                    /* strokes */5,
                                    /* fairway : NoFairway */0,
                                    /* green : MissLeftLong */3,
                                    /* putts */2
                                  ],
                                  /* :: */[
                                    /* record */[
                                      /* strokes */5,
                                      /* fairway : MissLeft */2,
                                      /* green : MissShort */8,
                                      /* putts */2
                                    ],
                                    /* [] */0
                                  ]
                                ]
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]
  ]
];

var round1 = /* record */[
  /* course */eastmoreland,
  /* date */"2018-05-27",
  round1_002
];

console.log(totalScore(round1));

console.log(percentFIR(round1_002));

console.log(percentGIR(round1_002));

console.log(totalPutts(round1_002));

exports.holeFactory = holeFactory;
exports.scoreFactory = scoreFactory;
exports.totalYards = totalYards;
exports.eastmoreland = eastmoreland;
exports.totalScore = totalScore;
exports.percentFIR = percentFIR;
exports.percentGIR = percentGIR;
exports.totalPutts = totalPutts;
exports.round1 = round1;
/*  Not a pure module */
