// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");
var Rounds$GolfStats = require("./Rounds.bs.js");

function total(nums) {
  return List.fold_left((function (sum, cur) {
                return sum + cur | 0;
              }), 0, nums);
}

function totalYards(course) {
  return total(List.map((function (hole) {
                    return hole[/* yards */2];
                  }), course[/* holes */1]));
}

function totalScore(round) {
  return total(List.map((function (score) {
                    return score[/* strokes */0];
                  }), round[/* scores */2]));
}

function percentFIR(scores) {
  var fairways = List.filter((function (fairway) {
            return fairway !== 0;
          }))(List.map((function (score) {
              return score[/* fairway */1];
            }), scores));
  var totalFairwaysHit = List.fold_left((function (acc, cur) {
          if (cur !== 1) {
            return acc;
          } else {
            return acc + 1 | 0;
          }
        }), 0, List.map((function (score) {
              return score[/* fairway */1];
            }), scores));
  return totalFairwaysHit / List.length(fairways);
}

function percentGIR(scores) {
  var totalGreensHit = List.fold_left((function (acc, cur) {
          if (cur !== 0) {
            return acc;
          } else {
            return acc + 1 | 0;
          }
        }), 0, List.map((function (score) {
              return score[/* green */2];
            }), scores));
  return totalGreensHit / List.length(scores);
}

function totalPutts(scores) {
  return total(List.map((function (score) {
                    return score[/* putts */3];
                  }), scores));
}

console.log("Total Score: " + String(totalScore(Rounds$GolfStats.round1)));

console.log("FIR: " + Pervasives.string_of_float(percentFIR(Rounds$GolfStats.round1[/* scores */2])));

console.log("GIR: " + Pervasives.string_of_float(percentGIR(Rounds$GolfStats.round1[/* scores */2])));

console.log("Total Putts: " + String(totalPutts(Rounds$GolfStats.round1[/* scores */2])));

exports.total = total;
exports.totalYards = totalYards;
exports.totalScore = totalScore;
exports.percentFIR = percentFIR;
exports.percentGIR = percentGIR;
exports.totalPutts = totalPutts;
/*  Not a pure module */
