// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Courses$GolfStats = require("./Courses.bs.js");

function scoreFactory(strokes, fairway, green, putts) {
  return /* record */[
          /* strokes */strokes,
          /* fairway */fairway,
          /* green */green,
          /* putts */putts
        ];
}

var round1_002 = /* scores : :: */[
  /* record */[
    /* strokes */3,
    /* fairway : Yes */1,
    /* green : Yes */0,
    /* putts */1
  ],
  /* :: */[
    /* record */[
      /* strokes */5,
      /* fairway : Yes */1,
      /* green : MissLeft */2,
      /* putts */2
    ],
    /* :: */[
      /* record */[
        /* strokes */4,
        /* fairway : Yes */1,
        /* green : Yes */0,
        /* putts */2
      ],
      /* :: */[
        /* record */[
          /* strokes */5,
          /* fairway : Yes */1,
          /* green : Yes */0,
          /* putts */3
        ],
        /* :: */[
          /* record */[
            /* strokes */3,
            /* fairway : NoFairway */0,
            /* green : Yes */0,
            /* putts */2
          ],
          /* :: */[
            /* record */[
              /* strokes */5,
              /* fairway : MissRight */3,
              /* green : Yes */0,
              /* putts */2
            ],
            /* :: */[
              /* record */[
                /* strokes */4,
                /* fairway : Yes */1,
                /* green : MissShort */8,
                /* putts */1
              ],
              /* :: */[
                /* record */[
                  /* strokes */4,
                  /* fairway : NoFairway */0,
                  /* green : MissShort */8,
                  /* putts */1
                ],
                /* :: */[
                  /* record */[
                    /* strokes */6,
                    /* fairway : MissRight */3,
                    /* green : MissRight */6,
                    /* putts */2
                  ],
                  /* :: */[
                    /* record */[
                      /* strokes */4,
                      /* fairway : Yes */1,
                      /* green : Yes */0,
                      /* putts */2
                    ],
                    /* :: */[
                      /* record */[
                        /* strokes */5,
                        /* fairway : MissLeft */2,
                        /* green : Yes */0,
                        /* putts */2
                      ],
                      /* :: */[
                        /* record */[
                          /* strokes */3,
                          /* fairway : NoFairway */0,
                          /* green : MissLeft */2,
                          /* putts */1
                        ],
                        /* :: */[
                          /* record */[
                            /* strokes */4,
                            /* fairway : MissRight */3,
                            /* green : Yes */0,
                            /* putts */2
                          ],
                          /* :: */[
                            /* record */[
                              /* strokes */4,
                              /* fairway : Yes */1,
                              /* green : MissShort */8,
                              /* putts */1
                            ],
                            /* :: */[
                              /* record */[
                                /* strokes */7,
                                /* fairway : Yes */1,
                                /* green : MissLeft */2,
                                /* putts */1
                              ],
                              /* :: */[
                                /* record */[
                                  /* strokes */5,
                                  /* fairway : Yes */1,
                                  /* green : Yes */0,
                                  /* putts */3
                                ],
                                /* :: */[
                                  /* record */[
                                    /* strokes */5,
                                    /* fairway : NoFairway */0,
                                    /* green : MissLeftLong */3,
                                    /* putts */2
                                  ],
                                  /* :: */[
                                    /* record */[
                                      /* strokes */5,
                                      /* fairway : MissLeft */2,
                                      /* green : MissShort */8,
                                      /* putts */2
                                    ],
                                    /* [] */0
                                  ]
                                ]
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]
  ]
];

var round1 = /* record */[
  /* course */Courses$GolfStats.eastmoreland,
  /* date */"2018-05-27",
  round1_002
];

var round2_002 = /* scores : :: */[
  /* record */[
    /* strokes */3,
    /* fairway : Yes */1,
    /* green : Yes */0,
    /* putts */1
  ],
  /* :: */[
    /* record */[
      /* strokes */4,
      /* fairway : MissLeft */2,
      /* green : MissLong */4,
      /* putts */2
    ],
    /* :: */[
      /* record */[
        /* strokes */4,
        /* fairway : Yes */1,
        /* green : Yes */0,
        /* putts */2
      ],
      /* :: */[
        /* record */[
          /* strokes */4,
          /* fairway : Yes */1,
          /* green : Yes */0,
          /* putts */2
        ],
        /* :: */[
          /* record */[
            /* strokes */2,
            /* fairway : NoFairway */0,
            /* green : Yes */0,
            /* putts */1
          ],
          /* :: */[
            /* record */[
              /* strokes */5,
              /* fairway : Yes */1,
              /* green : Yes */0,
              /* putts */2
            ],
            /* :: */[
              /* record */[
                /* strokes */5,
                /* fairway : MissLeft */2,
                /* green : MissLeft */2,
                /* putts */2
              ],
              /* :: */[
                /* record */[
                  /* strokes */2,
                  /* fairway : NoFairway */0,
                  /* green : Yes */0,
                  /* putts */1
                ],
                /* :: */[
                  /* record */[
                    /* strokes */5,
                    /* fairway : MissLeft */2,
                    /* green : Yes */0,
                    /* putts */2
                  ],
                  /* :: */[
                    /* record */[
                      /* strokes */5,
                      /* fairway : Yes */1,
                      /* green : MissShort */8,
                      /* putts */1
                    ],
                    /* :: */[
                      /* record */[
                        /* strokes */6,
                        /* fairway : Yes */1,
                        /* green : MissRight */6,
                        /* putts */1
                      ],
                      /* :: */[
                        /* record */[
                          /* strokes */4,
                          /* fairway : NoFairway */0,
                          /* green : Yes */0,
                          /* putts */3
                        ],
                        /* :: */[
                          /* record */[
                            /* strokes */5,
                            /* fairway : Yes */1,
                            /* green : Yes */0,
                            /* putts */3
                          ],
                          /* :: */[
                            /* record */[
                              /* strokes */5,
                              /* fairway : Yes */1,
                              /* green : MissShort */8,
                              /* putts */2
                            ],
                            /* :: */[
                              /* record */[
                                /* strokes */4,
                                /* fairway : Yes */1,
                                /* green : Yes */0,
                                /* putts */2
                              ],
                              /* :: */[
                                /* record */[
                                  /* strokes */4,
                                  /* fairway : Yes */1,
                                  /* green : Yes */0,
                                  /* putts */2
                                ],
                                /* :: */[
                                  /* record */[
                                    /* strokes */3,
                                    /* fairway : NoFairway */0,
                                    /* green : Yes */0,
                                    /* putts */2
                                  ],
                                  /* :: */[
                                    /* record */[
                                      /* strokes */5,
                                      /* fairway : Yes */1,
                                      /* green : Yes */0,
                                      /* putts */3
                                    ],
                                    /* [] */0
                                  ]
                                ]
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]
  ]
];

var round2 = /* record */[
  /* course */Courses$GolfStats.eastmoreland,
  /* date */"2018-06-24",
  round2_002
];

exports.scoreFactory = scoreFactory;
exports.round1 = round1;
exports.round2 = round2;
/* No side effect */
